/**
 * Converts a time interval (period + unit) into a cron expression.
 * Supports "minutes", "hours", "days", "weeks", and "months".
 */
export function toCron({
  period,
  unit,
}: {
  period: number;
  unit: "minutes" | "hours" | "days" | "weeks" | "months";
}): string {
  switch (unit) {
    case "minutes":
      return `*/${period} * * * *`;
    case "hours":
      return `0 */${period} * * *`;
    case "days":
      return `0 0 */${period} * *`;
    case "weeks":
      // Run every N weeks on Sunday at midnight
      // Note: native cron syntax can’t express “every N weeks” exactly;
      // this runs weekly (or every week multiple if handled externally)
      return `0 0 * * 0`;
    case "months":
      return `0 0 1 */${period} *`;
    default:
      throw new Error(`Unsupported unit: ${unit}`);
  }
}

/**
 * Converts a cron expression (5-field syntax) back into a { period, unit } object.
 * Only supports the formats generated by `toCron()`.
 */
export function fromCron(cron: string): { period: number; unit: string } {
  const parts = cron.trim().split(/\s+/);

  if (parts.length !== 5) {
    throw new Error(`Invalid cron expression: "${cron}"`);
  }

  const [minute, hour, day, month, weekday] = parts;

  // Every N minutes
  if (minute.startsWith("*/")) {
    return { period: parseInt(minute.slice(2), 10), unit: "minutes" };
  }

  // Every N hours
  if (hour.startsWith("*/")) {
    return { period: parseInt(hour.slice(2), 10), unit: "hours" };
  }

  // Every N days
  if (day.startsWith("*/")) {
    return { period: parseInt(day.slice(2), 10), unit: "days" };
  }

  // Every week (runs on Sunday)
  if (weekday === "0") {
    return { period: 1, unit: "weeks" };
  }

  // Every N months (on the 1st)
  if (month.startsWith("*/")) {
    return { period: parseInt(month.slice(2), 10), unit: "months" };
  }

  throw new Error(`Unsupported or unrecognized cron pattern: "${cron}"`);
}
